services:
  - type: web
    name: youtube-downloader
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app
    plan: free
